name: Compile all

on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        week: [
            "00_Orga",
            "01_introduction",
            "02_data_sampling_and_probability",
            "03_visualization",
            "04_data_cleaning",
            "05_intro_modelling",
            "06_learning",
            "07_classification",
            "08_bias_and_variance",
            "085_dim_red",
            "075_deep_learning",
            "09_deep_learning",
            "10_evaluation",
            "11_feature_engineering"
          ]
        mode: [
        #        "animation",
                "handout",
        ]
    steps:
      - uses: actions/checkout@v3
      - name: compile week ${{ matrix.week }} with xelatex
        uses: ./.github/actions/xelatex-week
        with:
          folder: ${{ matrix.week }}
          mode: ${{ matrix.mode }}
      - uses: actions/upload-artifact@v3
        with:
          name: Slides ${{ matrix.week }} (${{ matrix.mode }})
          path: ${{ matrix.week }}/${{ matrix.mode }}/*.pdf
  merge:
    name: Merge slides
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        week: [
            "00_Orga",
            "01_introduction",
            "02_data_sampling_and_probability",
            "03_visualization",
            "04_data_cleaning",
            "05_intro_modelling",
            "06_learning",
            "07_classification",
            "08_bias_and_variance",
            "085_dim_red",
            "075_deep_learning",
            "09_deep_learning",
            "10_evaluation",
            "11_feature_engineering"
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Slides ${{ matrix.week }} (handout)
          path: ${{ matrix.week }}/
      - name: Prepare output folder
        run: sh -c "[ -d slides ] || mkdir slides"
      - name: Merge slides for week ${{ matrix.week }} with pdftk
        uses: ./.github/actions/merge-pdftk
        with:
          input-pattern: ${{ matrix.week }}/t*.pdf
          output-name: slides/${{ matrix.week }}.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: Merged slides
          path: slides/*.pdf
